miky_grid:
    templates:
        batch_action: "MikyAdminBundle:Grid/BatchAction:batch_action.html.twig"
        action:
            show: "MikyAdminBundle:Grid/Action:show.html.twig"
            create: "MikyAdminBundle:Grid/Action:create.html.twig"
            update: "MikyAdminBundle:Grid/Action:update.html.twig"
            delete: "MikyAdminBundle:Grid/Action:delete.html.twig"
            validate: "MikyAdminBundle:Grid/Action:validate.html.twig"
            duplicate: "MikyAdminBundle:Grid/Action:duplicate.html.twig"
            preview: "MikyAdminBundle:Grid/Action:preview.html.twig"
            generator: "MikyAdminBundle:Grid/Action:generator.html.twig"
        filter:
            string: "MikyAdminBundle:Grid/Filter:string.html.twig"
            translatable_string: "MikyAdminBundle:Grid/Filter:string.html.twig"
            boolean: "MikyAdminBundle:Grid/Filter:boolean.html.twig"

