miky_admin_admin_redirect:
    path:      /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: miky_admin_admin_dashboard
        permanent: true

miky_admin_admin_dashboard:
    path:      /dashboard
    defaults: { _controller: MikyAdminBundle:Admin/Dashboard:index}